export const selectIsBusinessOwner = (state) => state.isBusinessOwner;
export const selectLiked = (state) => state.liked;
export const selectBusinesses = (state) => state.businesses;
export const selectJwt = (state) => state.jwt;
export const selectLoginInfo = (state) => state.loginInfo;
export const selectEditingAdding = (state) => state.editingAdding;
export const selectMyBusinesses = (state) => state.myBusiness;
export const selectbusinessToEdit = (state) => state.businessToEdit;
export const selectFilters = (state) => state.filters;
export const selectIdsToDisplay= (state) => state.idsToDisplay;